name          = "EMD"
authors       = ["Jeff Harrison"]
uuid          = "592af9be-fb4c-4ea1-98aa-327eb6946b76"
version       = "0.1.0"

[deps]
Dierckx       = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"

[compat]
julia         = "1.6"